<<<<<<< HEAD
package esercitazione.thread;

import java.util.ArrayList;

public class EsercitazioneThread {
    public static void main(String[] args) {

        final int numProduttori = Integer.parseInt(args[0]);
        final int numConsumatori = Integer.parseInt(args[1]);
        final int intervalloProduzione = Integer.parseInt(args[2]);
        final int maxDiffConsumo = Integer.parseInt(args[3]);
        final int dimensioneBuff = Integer.parseInt(args[4]);

        Product.maxConsumptionDifficulty = maxDiffConsumo;
        ArrayList<Worker> threads = new ArrayList<Worker>();
        Buffer<Product> sharedData = new Buffer<Product>(dimensioneBuff);

        // creo il numero di consumatori che si dovranno avere
=======
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package esercitazione.thread;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.ArrayList;

/**
 *
 * @author Ale
 */
public class EsercitazioneThread extends javax.swing.JFrame {

    /**
     * Creates new form InterfacciaGrafica
     */
    
Font FontMinecraft;
private int numProduttori;
private int numConsumatori;
private int intervalloProduzione;
private static int maxDiffConsumo;
private int dimensioneBuff;


ArrayList<Worker> threads;
Buffer<Product> sharedData;
    
    public EsercitazioneThread() {
        
        initComponents();

        threads = new ArrayList<Worker>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogVariabili = new javax.swing.JDialog();
        PanelVariabili = new javax.swing.JPanel();
        BottoneConferma = new javax.swing.JButton();
        LabelNumeroProduttori = new javax.swing.JLabel();
        LabelNumeroConsumatori = new javax.swing.JLabel();
        LabelIntervalloProduzione = new javax.swing.JLabel();
        LabelDifficoltaConsumo = new javax.swing.JLabel();
        LabelDimensioneBuffer = new javax.swing.JLabel();
        TextNumeroProduttori = new javax.swing.JTextField();
        TextNumeroConsumatori = new javax.swing.JTextField();
        TextIntervalloProduzione = new javax.swing.JTextField();
        TextDimensioneBuffer = new javax.swing.JTextField();
        TextDifficoltaConsumo = new javax.swing.JTextField();
        DialogMinore0 = new javax.swing.JDialog();
        LabelMinore0 = new javax.swing.JLabel();
        BottoneMinore0 = new javax.swing.JButton();
        DialogNonNumero = new javax.swing.JDialog();
        LabelNonNumero = new javax.swing.JLabel();
        BottoneNonNumero = new javax.swing.JButton();
        DialogNonValori = new javax.swing.JDialog();
        LabelNonValori = new javax.swing.JLabel();
        BottoneNonValori = new javax.swing.JButton();
        PanelLaterale = new javax.swing.JPanel();
        BottoneEsci = new javax.swing.JButton();
        BottoneInizia = new javax.swing.JButton();
        BottoneParametri = new javax.swing.JButton();
        PanelThread = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaProduttori = new javax.swing.JTextArea();
        PanelBuffer = new javax.swing.JPanel();
        LabelProduttori = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextAreaConsumatori = new javax.swing.JTextArea();
        LabelConsumatori = new javax.swing.JLabel();

        BottoneConferma.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BottoneConferma.setText("CONFERMA");
        BottoneConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottoneConfermaActionPerformed(evt);
            }
        });

        LabelNumeroProduttori.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelNumeroProduttori.setText("Numero Produttori");

        LabelNumeroConsumatori.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelNumeroConsumatori.setText("Numero Consumatori");

        LabelIntervalloProduzione.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelIntervalloProduzione.setText("Intervallo di Produzione");

        LabelDifficoltaConsumo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelDifficoltaConsumo.setText("Difficoltà massima consumo");

        LabelDimensioneBuffer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelDimensioneBuffer.setText("Dimensione buffer");

        javax.swing.GroupLayout PanelVariabiliLayout = new javax.swing.GroupLayout(PanelVariabili);
        PanelVariabili.setLayout(PanelVariabiliLayout);
        PanelVariabiliLayout.setHorizontalGroup(
            PanelVariabiliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BottoneConferma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelVariabiliLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(PanelVariabiliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNumeroProduttori, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDifficoltaConsumo)
                    .addComponent(LabelDimensioneBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelIntervalloProduzione, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNumeroConsumatori, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(PanelVariabiliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextNumeroProduttori, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextNumeroConsumatori, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextIntervalloProduzione, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextDimensioneBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextDifficoltaConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );
        PanelVariabiliLayout.setVerticalGroup(
            PanelVariabiliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVariabiliLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(PanelVariabiliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNumeroProduttori, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextNumeroProduttori, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelVariabiliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNumeroConsumatori, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextNumeroConsumatori, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelVariabiliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIntervalloProduzione, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextIntervalloProduzione, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelVariabiliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDifficoltaConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextDifficoltaConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelVariabiliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDimensioneBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextDimensioneBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BottoneConferma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout DialogVariabiliLayout = new javax.swing.GroupLayout(DialogVariabili.getContentPane());
        DialogVariabili.getContentPane().setLayout(DialogVariabiliLayout);
        DialogVariabiliLayout.setHorizontalGroup(
            DialogVariabiliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelVariabili, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogVariabiliLayout.setVerticalGroup(
            DialogVariabiliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelVariabili, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        LabelMinore0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelMinore0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelMinore0.setText("I valori inseriti devono essere maggiore di 0");

        BottoneMinore0.setText("Conferma");
        BottoneMinore0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottoneMinore0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogMinore0Layout = new javax.swing.GroupLayout(DialogMinore0.getContentPane());
        DialogMinore0.getContentPane().setLayout(DialogMinore0Layout);
        DialogMinore0Layout.setHorizontalGroup(
            DialogMinore0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelMinore0, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
            .addComponent(BottoneMinore0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogMinore0Layout.setVerticalGroup(
            DialogMinore0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogMinore0Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LabelMinore0, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BottoneMinore0, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
        );

        LabelNonNumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelNonNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNonNumero.setText("I valori inseriti devono essere numeri");

        BottoneNonNumero.setText("Conferma");
        BottoneNonNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottoneNonNumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogNonNumeroLayout = new javax.swing.GroupLayout(DialogNonNumero.getContentPane());
        DialogNonNumero.getContentPane().setLayout(DialogNonNumeroLayout);
        DialogNonNumeroLayout.setHorizontalGroup(
            DialogNonNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelNonNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
            .addComponent(BottoneNonNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogNonNumeroLayout.setVerticalGroup(
            DialogNonNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogNonNumeroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LabelNonNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BottoneNonNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
        );

        LabelNonValori.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelNonValori.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNonValori.setText("Inizializzare i valori prima di iniziare");

        BottoneNonValori.setText("Conferma");
        BottoneNonValori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottoneNonValoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogNonValoriLayout = new javax.swing.GroupLayout(DialogNonValori.getContentPane());
        DialogNonValori.getContentPane().setLayout(DialogNonValoriLayout);
        DialogNonValoriLayout.setHorizontalGroup(
            DialogNonValoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelNonValori, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
            .addComponent(BottoneNonValori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogNonValoriLayout.setVerticalGroup(
            DialogNonValoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogNonValoriLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LabelNonValori, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BottoneNonValori, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Produttori e Consumatori");

        PanelLaterale.setBackground(new java.awt.Color(0, 102, 51));
        PanelLaterale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BottoneEsci.setBackground(new java.awt.Color(255, 0, 0));
        BottoneEsci.setText("ESCI");
        BottoneEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottoneEsciActionPerformed(evt);
            }
        });

        BottoneInizia.setBackground(new java.awt.Color(51, 153, 255));
        BottoneInizia.setText("INIZIA");
        BottoneInizia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottoneIniziaActionPerformed(evt);
            }
        });

        BottoneParametri.setBackground(new java.awt.Color(153, 255, 51));
        BottoneParametri.setText("PARAMETRI ");
        BottoneParametri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottoneParametriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLateraleLayout = new javax.swing.GroupLayout(PanelLaterale);
        PanelLaterale.setLayout(PanelLateraleLayout);
        PanelLateraleLayout.setHorizontalGroup(
            PanelLateraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BottoneEsci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BottoneInizia, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(BottoneParametri, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        PanelLateraleLayout.setVerticalGroup(
            PanelLateraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLateraleLayout.createSequentialGroup()
                .addContainerGap(453, Short.MAX_VALUE)
                .addComponent(BottoneParametri, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BottoneInizia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BottoneEsci, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        PanelThread.setBackground(new java.awt.Color(0, 102, 102));
        PanelThread.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TextAreaProduttori.setEditable(false);
        TextAreaProduttori.setColumns(20);
        TextAreaProduttori.setFont(new java.awt.Font("Monocraft", 0, 12)); // NOI18N
        TextAreaProduttori.setRows(10);
        jScrollPane1.setViewportView(TextAreaProduttori);

        PanelBuffer.setBackground(new java.awt.Color(0, 102, 102));
        PanelBuffer.setLayout(new java.awt.GridLayout(10000, 7));

        LabelProduttori.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LabelProduttori.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelProduttori.setText("Produttori");

        TextAreaConsumatori.setEditable(false);
        TextAreaConsumatori.setColumns(20);
        TextAreaConsumatori.setFont(new java.awt.Font("Monocraft", 0, 12)); // NOI18N
        TextAreaConsumatori.setRows(10);
        jScrollPane3.setViewportView(TextAreaConsumatori);

        LabelConsumatori.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LabelConsumatori.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelConsumatori.setText("Consumatori");

        javax.swing.GroupLayout PanelThreadLayout = new javax.swing.GroupLayout(PanelThread);
        PanelThread.setLayout(PanelThreadLayout);
        PanelThreadLayout.setHorizontalGroup(
            PanelThreadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelThreadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelThreadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(LabelProduttori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelThreadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelThreadLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3))
                    .addComponent(LabelConsumatori, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelThreadLayout.setVerticalGroup(
            PanelThreadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelThreadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelThreadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelThreadLayout.createSequentialGroup()
                        .addComponent(LabelConsumatori, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addComponent(PanelBuffer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelThreadLayout.createSequentialGroup()
                        .addComponent(LabelProduttori, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelLaterale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelThread, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLaterale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelThread, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BottoneConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottoneConfermaActionPerformed
        ControlloTesto();
    }//GEN-LAST:event_BottoneConfermaActionPerformed

    private void BottoneMinore0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottoneMinore0ActionPerformed
        DialogMinore0.dispose();
    }//GEN-LAST:event_BottoneMinore0ActionPerformed

    private void BottoneNonNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottoneNonNumeroActionPerformed
        DialogNonNumero.dispose();
    }//GEN-LAST:event_BottoneNonNumeroActionPerformed

    private void BottoneEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottoneEsciActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_BottoneEsciActionPerformed

    private void BottoneIniziaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottoneIniziaActionPerformed
        // TODO add your handling code here:
        if(numProduttori!=0){
            InizioThread();
        }
        else {
            DialogNonValori.setSize(400,200);
            DialogNonValori.setLocationRelativeTo(this);
            DialogNonValori.setVisible(true);
        }
    }//GEN-LAST:event_BottoneIniziaActionPerformed

    private void BottoneNonValoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottoneNonValoriActionPerformed
        DialogNonValori.dispose();

    }//GEN-LAST:event_BottoneNonValoriActionPerformed

    private void BottoneParametriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottoneParametriActionPerformed
        // TODO add your handling code here:
        DialogVariabili.setSize(600,390);
        DialogVariabili.setLocationRelativeTo(this);
        DialogVariabili.setVisible(true);
    }//GEN-LAST:event_BottoneParametriActionPerformed

    public void ControlloTesto(){
                
        try{
  
            numProduttori=Integer.parseInt(TextNumeroProduttori.getText());
            numConsumatori=Integer.parseInt(TextNumeroConsumatori.getText());
            intervalloProduzione=Integer.parseInt(TextIntervalloProduzione.getText());
            Product.maxConsumptionDifficulty=Integer.parseInt(TextDifficoltaConsumo.getText());
            maxDiffConsumo=Integer.parseInt(TextDifficoltaConsumo.getText());
            dimensioneBuff=Integer.parseInt(TextDimensioneBuffer.getText());
            sharedData = new Buffer<Product>(dimensioneBuff);
            
            
            if(numProduttori< 0 || numConsumatori< 0 || intervalloProduzione< 0 || maxDiffConsumo< 0 || dimensioneBuff< 0 ){
                DialogMinore0.setSize(400,200);
                DialogMinore0.setLocationRelativeTo(this);
                DialogMinore0.setVisible(true);
            }else {
                DialogVariabili.dispose();         
            }
            
        }catch(NumberFormatException e){
            
            DialogNonNumero.setSize(400,200);
            DialogNonNumero.setLocationRelativeTo(this);
            DialogNonNumero.setVisible(true);
            
        }
        
        
        
    }
    
    public void InizioThread(){
        if(sharedData == null){
            System.out.print("buffer e' null");
        } else{
            System.out.print("buffer inizializzato");
        }

        
         // creo il numero di consumatori che si dovranno avere
>>>>>>> b6c2a02 (Aggiunta la parte grafica iniziale)
        for (int i = 0; i < numProduttori; i++) {
            threads.add(new Producer(intervalloProduzione, sharedData, i + 1));
        }

        // creo il numero di produttori che si dovranno avere
        for (int i = 0; i < numConsumatori; i++) {
            threads.add(new Consumer(sharedData, i + 1));
        }

        // avvio la simulazione con tutti i thread
        for (Worker worker : threads) {
            worker.start();
        }
<<<<<<< HEAD
    }
=======
        
    }
    
    
    public static void main(String[] args) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EsercitazioneThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EsercitazioneThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EsercitazioneThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EsercitazioneThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EsercitazioneThread().setVisible(true);
            }
        });

       
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BottoneConferma;
    private javax.swing.JButton BottoneEsci;
    private javax.swing.JButton BottoneInizia;
    private javax.swing.JButton BottoneMinore0;
    private javax.swing.JButton BottoneNonNumero;
    private javax.swing.JButton BottoneNonValori;
    private javax.swing.JButton BottoneParametri;
    private javax.swing.JDialog DialogMinore0;
    private javax.swing.JDialog DialogNonNumero;
    private javax.swing.JDialog DialogNonValori;
    private javax.swing.JDialog DialogVariabili;
    private javax.swing.JLabel LabelConsumatori;
    private javax.swing.JLabel LabelDifficoltaConsumo;
    private javax.swing.JLabel LabelDimensioneBuffer;
    private javax.swing.JLabel LabelIntervalloProduzione;
    private javax.swing.JLabel LabelMinore0;
    private javax.swing.JLabel LabelNonNumero;
    private javax.swing.JLabel LabelNonValori;
    private javax.swing.JLabel LabelNumeroConsumatori;
    private javax.swing.JLabel LabelNumeroProduttori;
    private javax.swing.JLabel LabelProduttori;
    private javax.swing.JPanel PanelBuffer;
    private javax.swing.JPanel PanelLaterale;
    private javax.swing.JPanel PanelThread;
    private javax.swing.JPanel PanelVariabili;
    public static javax.swing.JTextArea TextAreaConsumatori;
    public static javax.swing.JTextArea TextAreaProduttori;
    private javax.swing.JTextField TextDifficoltaConsumo;
    private javax.swing.JTextField TextDimensioneBuffer;
    private javax.swing.JTextField TextIntervalloProduzione;
    private javax.swing.JTextField TextNumeroConsumatori;
    private javax.swing.JTextField TextNumeroProduttori;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
>>>>>>> b6c2a02 (Aggiunta la parte grafica iniziale)
}
